
package com.askcs.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AskPortType", targetNamespace = "urn:webservices.askcs.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AskPortType {


    /**
     * 
     * @param authKey
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#startSession")
    @WebResult(partName = "return")
    public StringResponse startSession(
        @WebParam(name = "authKey", partName = "authKey")
        String authKey);

    /**
     * 
     * @param error
     * @param service
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getErrorMessage")
    @WebResult(partName = "return")
    public StringResponse getErrorMessage(
        @WebParam(name = "error", partName = "error")
        int error,
        @WebParam(name = "service", partName = "service")
        String service);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param data
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createNode")
    @WebResult(partName = "return")
    public StringResponse createNode(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeNode")
    @WebResult(partName = "return")
    public BoolResponse removeNode(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.TupleArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getNodeData")
    @WebResult(partName = "return")
    public TupleArrayResponse getNodeData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param data
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setNodeData")
    @WebResult(partName = "return")
    public BoolResponse setNodeData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getNodeContainers")
    @WebResult(partName = "return")
    public StringArrayResponse getNodeContainers(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param tag
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getNodeContainersByTag")
    @WebResult(partName = "return")
    public StringArrayResponse getNodeContainersByTag(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "tag", partName = "tag")
        String tag);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getNodeMembers")
    @WebResult(partName = "return")
    public StringArrayResponse getNodeMembers(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param tag
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getNodeMembersByTag")
    @WebResult(partName = "return")
    public StringArrayResponse getNodeMembersByTag(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "tag", partName = "tag")
        String tag);

    /**
     * 
     * @param sessionID
     * @param memUUID
     * @param parUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#attachNode")
    @WebResult(partName = "return")
    public BoolResponse attachNode(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "parUUID", partName = "parUUID")
        String parUUID,
        @WebParam(name = "memUUID", partName = "memUUID")
        String memUUID);

    /**
     * 
     * @param sessionID
     * @param memUUID
     * @param parUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#detachNode")
    @WebResult(partName = "return")
    public BoolResponse detachNode(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "parUUID", partName = "parUUID")
        String parUUID,
        @WebParam(name = "memUUID", partName = "memUUID")
        String memUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getServices")
    @WebResult(partName = "return")
    public StringArrayResponse getServices(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.IdArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getAddresses")
    @WebResult(partName = "return")
    public IdArrayResponse getAddresses(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getResources")
    @WebResult(partName = "return")
    public StringArrayResponse getResources(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.ResourceDataArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getResourcesData")
    @WebResult(partName = "return")
    public ResourceDataArrayResponse getResourcesData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param data
     * @param addrUUID
     * @param type
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createAddress")
    @WebResult(partName = "return")
    public StringResponse createAddress(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "addrUUID", partName = "addrUUID")
        String addrUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param sessionID
     * @param addrUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeAddress")
    @WebResult(partName = "return")
    public BoolResponse removeAddress(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "addrUUID", partName = "addrUUID")
        String addrUUID);

    /**
     * 
     * @param sessionID
     * @param addrUUID
     * @return
     *     returns com.askcs.webservices.TupleArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getAddressData")
    @WebResult(partName = "return")
    public TupleArrayResponse getAddressData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "addrUUID", partName = "addrUUID")
        String addrUUID);

    /**
     * 
     * @param sessionID
     * @param data
     * @param addrUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setAddressData")
    @WebResult(partName = "return")
    public BoolResponse setAddressData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "addrUUID", partName = "addrUUID")
        String addrUUID,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getAlgorithms")
    @WebResult(partName = "return")
    public StringArrayResponse getAlgorithms(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param direction
     * @param name
     * @param srvUUID
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createService")
    @WebResult(partName = "return")
    public StringResponse createService(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "direction", partName = "direction")
        String direction);

    /**
     * 
     * @param sessionID
     * @param srvUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeService")
    @WebResult(partName = "return")
    public BoolResponse removeService(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID);

    /**
     * 
     * @param sessionID
     * @param srvUUID
     * @return
     *     returns com.askcs.webservices.ServiceDataResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getServiceData")
    @WebResult(partName = "return")
    public ServiceDataResponse getServiceData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID);

    /**
     * 
     * @param sessionID
     * @param direction
     * @param name
     * @param srvUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setServiceData")
    @WebResult(partName = "return")
    public BoolResponse setServiceData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "direction", partName = "direction")
        String direction);

    /**
     * 
     * @param stateGroupUUID
     * @param sLayerUUID
     * @param sessionID
     * @param filterValue
     * @param filterDirection
     * @param description
     * @param gauge
     * @param availType
     * @param srvUUID
     * @param resourceTag
     * @param algorithm
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#addServiceLayerToService")
    @WebResult(partName = "return")
    public StringResponse addServiceLayerToService(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID,
        @WebParam(name = "sLayerUUID", partName = "sLayerUUID")
        String sLayerUUID,
        @WebParam(name = "algorithm", partName = "algorithm")
        String algorithm,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "availType", partName = "availType")
        int availType,
        @WebParam(name = "stateGroupUUID", partName = "stateGroupUUID")
        String stateGroupUUID,
        @WebParam(name = "filterDirection", partName = "filterDirection")
        int filterDirection,
        @WebParam(name = "filterValue", partName = "filterValue")
        float filterValue,
        @WebParam(name = "gauge", partName = "gauge")
        boolean gauge,
        @WebParam(name = "resourceTag", partName = "resourceTag")
        String resourceTag);

    /**
     * 
     * @param sLayerUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeServiceLayer")
    @WebResult(partName = "return")
    public BoolResponse removeServiceLayer(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sLayerUUID", partName = "sLayerUUID")
        String sLayerUUID);

    /**
     * 
     * @param sLayerUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.ServiceDataResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getServiceLayerData")
    @WebResult(partName = "return")
    public ServiceDataResponse getServiceLayerData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sLayerUUID", partName = "sLayerUUID")
        String sLayerUUID);

    /**
     * 
     * @param stateGroupUUID
     * @param sLayerUUID
     * @param sessionID
     * @param filterValue
     * @param filterDirection
     * @param description
     * @param gauge
     * @param availType
     * @param resourceTag
     * @param algorithm
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setServiceLayerData")
    @WebResult(partName = "return")
    public BoolResponse setServiceLayerData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sLayerUUID", partName = "sLayerUUID")
        String sLayerUUID,
        @WebParam(name = "algorithm", partName = "algorithm")
        String algorithm,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "availType", partName = "availType")
        int availType,
        @WebParam(name = "stateGroupUUID", partName = "stateGroupUUID")
        String stateGroupUUID,
        @WebParam(name = "filterDirection", partName = "filterDirection")
        int filterDirection,
        @WebParam(name = "filterValue", partName = "filterValue")
        float filterValue,
        @WebParam(name = "gauge", partName = "gauge")
        boolean gauge,
        @WebParam(name = "resourceTag", partName = "resourceTag")
        String resourceTag);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param planboard
     * @return
     *     returns com.askcs.webservices.LabelArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getLegend")
    @WebResult(partName = "return")
    public LabelArrayResponse getLegend(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param colour
     * @param sessionID
     * @param name
     * @param stateUUID
     * @param planboard
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createUserState")
    @WebResult(partName = "return")
    public StringResponse createUserState(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "colour", partName = "colour")
        String colour);

    /**
     * 
     * @param sessionID
     * @param stateUUID
     * @param planboard
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeUserState")
    @WebResult(partName = "return")
    public BoolResponse removeUserState(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard);

    /**
     * 
     * @param sessionID
     * @param stateUUID
     * @param planboard
     * @return
     *     returns com.askcs.webservices.StateDataResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getUserStateData")
    @WebResult(partName = "return")
    public StateDataResponse getUserStateData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard);

    /**
     * 
     * @param colour
     * @param sessionID
     * @param name
     * @param stateUUID
     * @param planboard
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setUserStateData")
    @WebResult(partName = "return")
    public BoolResponse setUserStateData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "colour", partName = "colour")
        String colour);

    /**
     * 
     * @param sessionID
     * @param stateUUID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getUserStateContainers")
    @WebResult(partName = "return")
    public StringArrayResponse getUserStateContainers(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID);

    /**
     * 
     * @param sessionID
     * @param name
     * @param sgrUUID
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createStateGroup")
    @WebResult(partName = "return")
    public StringResponse createStateGroup(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sgrUUID", partName = "sgrUUID")
        String sgrUUID,
        @WebParam(name = "name", partName = "name")
        String name);

    /**
     * 
     * @param sessionID
     * @param sgrUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeStateGroup")
    @WebResult(partName = "return")
    public BoolResponse removeStateGroup(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sgrUUID", partName = "sgrUUID")
        String sgrUUID);

    /**
     * 
     * @param sessionID
     * @param sgrUUID
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getStateGroupName")
    @WebResult(partName = "return")
    public StringResponse getStateGroupName(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sgrUUID", partName = "sgrUUID")
        String sgrUUID);

    /**
     * 
     * @param sessionID
     * @param name
     * @param sgrUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setStateGroupName")
    @WebResult(partName = "return")
    public BoolResponse setStateGroupName(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sgrUUID", partName = "sgrUUID")
        String sgrUUID,
        @WebParam(name = "name", partName = "name")
        String name);

    /**
     * 
     * @param sessionID
     * @param sgrUUID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getStateGroupMembers")
    @WebResult(partName = "return")
    public StringArrayResponse getStateGroupMembers(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sgrUUID", partName = "sgrUUID")
        String sgrUUID);

    /**
     * 
     * @param sessionID
     * @param stateUUID
     * @param sgrUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#attachUserState")
    @WebResult(partName = "return")
    public BoolResponse attachUserState(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sgrUUID", partName = "sgrUUID")
        String sgrUUID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID);

    /**
     * 
     * @param sessionID
     * @param stateUUID
     * @param sgrUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#detachUserState")
    @WebResult(partName = "return")
    public BoolResponse detachUserState(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sgrUUID", partName = "sgrUUID")
        String sgrUUID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param start
     * @param end
     * @param planboard
     * @return
     *     returns com.askcs.webservices.SlotDataArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getSlots")
    @WebResult(partName = "return")
    public SlotDataArrayResponse getSlots(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "start", partName = "start")
        int start,
        @WebParam(name = "end", partName = "end")
        int end);

    /**
     * 
     * @param nodeUUID
     * @param text
     * @param sessionID
     * @param start
     * @param method
     * @param label
     * @param end
     * @param planboard
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createSlot")
    @WebResult(partName = "return")
    public BoolResponse createSlot(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "start", partName = "start")
        int start,
        @WebParam(name = "end", partName = "end")
        int end,
        @WebParam(name = "label", partName = "label")
        String label,
        @WebParam(name = "method", partName = "method")
        String method,
        @WebParam(name = "text", partName = "text")
        String text);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param start
     * @param label
     * @param end
     * @param planboard
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeSlot")
    @WebResult(partName = "return")
    public BoolResponse removeSlot(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "start", partName = "start")
        int start,
        @WebParam(name = "end", partName = "end")
        int end,
        @WebParam(name = "label", partName = "label")
        String label);

    /**
     * 
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getBoxTypes")
    @WebResult(partName = "return")
    public StringArrayResponse getBoxTypes(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param type
     * @return
     *     returns com.askcs.webservices.TupleArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getBoxFields")
    @WebResult(partName = "return")
    public TupleArrayResponse getBoxFields(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "type", partName = "type")
        String type);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @param data
     * @param type
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createBox")
    @WebResult(partName = "return")
    public StringResponse createBox(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeBox")
    @WebResult(partName = "return")
    public BoolResponse removeBox(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.TupleArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getBoxData")
    @WebResult(partName = "return")
    public TupleArrayResponse getBoxData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @param data
     * @param type
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setBoxData")
    @WebResult(partName = "return")
    public BoolResponse setBoxData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param category
     * @param ownUUID
     * @param sessionID
     * @param tag
     * @param description
     * @param name
     * @param value
     * @param resUUID
     * @param type
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createResource")
    @WebResult(partName = "return")
    public StringResponse createResource(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "ownUUID", partName = "ownUUID")
        String ownUUID,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "category", partName = "category")
        String category,
        @WebParam(name = "tag", partName = "tag")
        String tag,
        @WebParam(name = "value", partName = "value")
        String value);

    /**
     * 
     * @param sessionID
     * @param resUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeResource")
    @WebResult(partName = "return")
    public BoolResponse removeResource(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID);

    /**
     * 
     * @param sessionID
     * @param resUUID
     * @return
     *     returns com.askcs.webservices.ResourceDataResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getResourceData")
    @WebResult(partName = "return")
    public ResourceDataResponse getResourceData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID);

    /**
     * 
     * @param ownUUID
     * @param sessionID
     * @param tag
     * @param type
     * @return
     *     returns com.askcs.webservices.ResourceDataResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getResourceDataByTag")
    @WebResult(partName = "return")
    public ResourceDataResponse getResourceDataByTag(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "ownUUID", partName = "ownUUID")
        String ownUUID,
        @WebParam(name = "tag", partName = "tag")
        String tag,
        @WebParam(name = "type", partName = "type")
        String type);

    /**
     * 
     * @param category
     * @param ownUUID
     * @param sessionID
     * @param tag
     * @param description
     * @param name
     * @param value
     * @param resUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setResourceData")
    @WebResult(partName = "return")
    public BoolResponse setResourceData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID,
        @WebParam(name = "ownUUID", partName = "ownUUID")
        String ownUUID,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "category", partName = "category")
        String category,
        @WebParam(name = "tag", partName = "tag")
        String tag,
        @WebParam(name = "value", partName = "value")
        String value);

    /**
     * 
     * @param sessionID
     * @param resUUID
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getDownloadURL")
    @WebResult(partName = "return")
    public StringResponse getDownloadURL(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID);

    /**
     * 
     * @param sessionID
     * @param resUUID
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getUploadURL")
    @WebResult(partName = "return")
    public StringResponse getUploadURL(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getJobTypes")
    @WebResult(partName = "return")
    public StringArrayResponse getJobTypes(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param type
     * @return
     *     returns com.askcs.webservices.TupleArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getJobFields")
    @WebResult(partName = "return")
    public TupleArrayResponse getJobFields(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "type", partName = "type")
        String type);

    /**
     * 
     * @param desc
     * @param sessionID
     * @param interval
     * @param jobUUID
     * @param params
     * @param type
     * @return
     *     returns com.askcs.webservices.StringResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#createJob")
    @WebResult(partName = "return")
    public StringResponse createJob(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "desc", partName = "desc")
        String desc,
        @WebParam(name = "interval", partName = "interval")
        int interval,
        @WebParam(name = "params", partName = "params")
        TupleArray params);

    /**
     * 
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeJob")
    @WebResult(partName = "return")
    public BoolResponse removeJob(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID);

    /**
     * 
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns com.askcs.webservices.JobDataResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getJobData")
    @WebResult(partName = "return")
    public JobDataResponse getJobData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID);

    /**
     * 
     * @param desc
     * @param sessionID
     * @param interval
     * @param jobUUID
     * @param params
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setJobData")
    @WebResult(partName = "return")
    public BoolResponse setJobData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "desc", partName = "desc")
        String desc,
        @WebParam(name = "interval", partName = "interval")
        int interval,
        @WebParam(name = "params", partName = "params")
        TupleArray params);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#attachJobToAgent")
    @WebResult(partName = "return")
    public BoolResponse attachJobToAgent(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#detachJobFromAgent")
    @WebResult(partName = "return")
    public BoolResponse detachJobFromAgent(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns com.askcs.webservices.StringArrayResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getJobAgents")
    @WebResult(partName = "return")
    public StringArrayResponse getJobAgents(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param range
     * @param jobUUID
     * @return
     *     returns com.askcs.webservices.TransitionResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getTransition")
    @WebResult(partName = "return")
    public TransitionResponse getTransition(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "range", partName = "range")
        int range);

    /**
     * 
     * @param nodeUUID
     * @param nextJobUUID
     * @param overlap
     * @param sessionID
     * @param range
     * @param length
     * @param jobUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setTransition")
    @WebResult(partName = "return")
    public BoolResponse setTransition(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "range", partName = "range")
        int range,
        @WebParam(name = "nextJobUUID", partName = "nextJobUUID")
        String nextJobUUID,
        @WebParam(name = "length", partName = "length")
        int length,
        @WebParam(name = "overlap", partName = "overlap")
        int overlap);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param range
     * @param jobUUID
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#removeTransition")
    @WebResult(partName = "return")
    public BoolResponse removeTransition(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "range", partName = "range")
        int range);

    /**
     * 
     * @param sessionID
     * @param childUUID
     * @param peerUUID
     * @param parentUUID
     * @param algorithm
     * @return
     *     returns com.askcs.webservices.IntResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#getRate")
    @WebResult(partName = "return")
    public IntResponse getRate(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "algorithm", partName = "algorithm")
        String algorithm,
        @WebParam(name = "parentUUID", partName = "parentUUID")
        String parentUUID,
        @WebParam(name = "childUUID", partName = "childUUID")
        String childUUID,
        @WebParam(name = "peerUUID", partName = "peerUUID")
        String peerUUID);

    /**
     * 
     * @param rate
     * @param sessionID
     * @param childUUID
     * @param peerUUID
     * @param parentUUID
     * @param algorithm
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#setRate")
    @WebResult(partName = "return")
    public BoolResponse setRate(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "algorithm", partName = "algorithm")
        String algorithm,
        @WebParam(name = "parentUUID", partName = "parentUUID")
        String parentUUID,
        @WebParam(name = "childUUID", partName = "childUUID")
        String childUUID,
        @WebParam(name = "peerUUID", partName = "peerUUID")
        String peerUUID,
        @WebParam(name = "rate", partName = "rate")
        float rate);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @param toUUID
     * @param fromUUID
     * @param type
     * @return
     *     returns com.askcs.webservices.BoolResponse
     */
    @WebMethod(action = "urn:webservices.askcs.com#triggerRequest")
    @WebResult(partName = "return")
    public BoolResponse triggerRequest(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "fromUUID", partName = "fromUUID")
        String fromUUID,
        @WebParam(name = "toUUID", partName = "toUUID")
        String toUUID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID,
        @WebParam(name = "type", partName = "type")
        String type);

}
