
package com.askcs.soaptoid;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * gSOAP 2.7.15 generated service definition
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "soaptoid", targetNamespace = "urn:soaptoid", wsdlLocation = "http://ask-dev.customers.luna.net/~carlo/txtxchange/webservices/index.doc.php?wsdl")
public class Soaptoid
    extends Service
{

    private final static URL SOAPTOID_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.askcs.soaptoid.Soaptoid.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.askcs.soaptoid.Soaptoid.class.getResource(".");
            url = new URL(baseUrl, "http://ask-dev.customers.luna.net/~carlo/txtxchange/webservices/index.doc.php?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ask-dev.customers.luna.net/~carlo/txtxchange/webservices/index.doc.php?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SOAPTOID_WSDL_LOCATION = url;
    }

    public Soaptoid(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Soaptoid() {
        super(SOAPTOID_WSDL_LOCATION, new QName("urn:soaptoid", "soaptoid"));
    }

    /**
     * 
     * @return
     *     returns SoaptoidPortType
     */
    @WebEndpoint(name = "soaptoid")
    public SoaptoidPortType getSoaptoid() {
        return super.getPort(new QName("urn:soaptoid", "soaptoid"), SoaptoidPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoaptoidPortType
     */
    @WebEndpoint(name = "soaptoid")
    public SoaptoidPortType getSoaptoid(WebServiceFeature... features) {
        return super.getPort(new QName("urn:soaptoid", "soaptoid"), SoaptoidPortType.class, features);
    }

}
