
package com.askcs.soaptoid;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "soaptoidPortType", targetNamespace = "urn:soaptoid")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoaptoidPortType {


    /**
     * Service definition of function ns1__doCall
     * 
     * @param oSessionID
     * @param iSessionID
     * @param answer
     * @param question
     */
    @WebMethod
    @RequestWrapper(localName = "doCall", targetNamespace = "urn:soaptoid", className = "com.askcs.soaptoid.DoCall")
    @ResponseWrapper(localName = "doCallResponse", targetNamespace = "urn:soaptoid", className = "com.askcs.soaptoid.DoCallResponse")
    public void doCall(
        @WebParam(name = "iSessionID", targetNamespace = "urn:soaptoid")
        java.lang.Integer iSessionID,
        @WebParam(name = "question", targetNamespace = "urn:soaptoid")
        java.lang.String question,
        @WebParam(name = "oSessionID", targetNamespace = "urn:soaptoid", mode = WebParam.Mode.OUT)
        Holder<java.lang.Integer> oSessionID,
        @WebParam(name = "answer", targetNamespace = "urn:soaptoid", mode = WebParam.Mode.OUT)
        Holder<java.lang.String> answer);

}
