
package cs.ask.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AskPortType", targetNamespace = "urn:com.ask-cs")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AskPortType {


    /**
     * 
     * @param authKey
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#startSession")
    @WebResult(partName = "return")
    public StringResponse startSession(
        @WebParam(name = "authKey", partName = "authKey")
        String authKey);

    /**
     * 
     * @param error
     * @param service
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getErrorMessage")
    @WebResult(partName = "return")
    public StringResponse getErrorMessage(
        @WebParam(name = "error", partName = "error")
        int error,
        @WebParam(name = "service", partName = "service")
        String service);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param data
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#createNode")
    @WebResult(partName = "return")
    public StringResponse createNode(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeNode")
    @WebResult(partName = "return")
    public BoolResponse removeNode(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.TupleArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getNodeData")
    @WebResult(partName = "return")
    public TupleArrayResponse getNodeData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param data
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setNodeData")
    @WebResult(partName = "return")
    public BoolResponse setNodeData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getNodeContainers")
    @WebResult(partName = "return")
    public StringArrayResponse getNodeContainers(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param tag
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getNodeContainersByTag")
    @WebResult(partName = "return")
    public StringArrayResponse getNodeContainersByTag(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "tag", partName = "tag")
        String tag);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getNodeMembers")
    @WebResult(partName = "return")
    public StringArrayResponse getNodeMembers(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param tag
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getNodeMembersByTag")
    @WebResult(partName = "return")
    public StringArrayResponse getNodeMembersByTag(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "tag", partName = "tag")
        String tag);

    /**
     * 
     * @param sessionID
     * @param uuid
     * @param parUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#attachNode")
    @WebResult(partName = "return")
    public BoolResponse attachNode(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "parUUID", partName = "parUUID")
        String parUUID,
        @WebParam(name = "UUID", partName = "UUID")
        String uuid);

    /**
     * 
     * @param sessionID
     * @param memUUID
     * @param parUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#detachNode")
    @WebResult(partName = "return")
    public BoolResponse detachNode(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "parUUID", partName = "parUUID")
        String parUUID,
        @WebParam(name = "memUUID", partName = "memUUID")
        String memUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getServices")
    @WebResult(partName = "return")
    public StringArrayResponse getServices(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.IdArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getAddresses")
    @WebResult(partName = "return")
    public IdArrayResponse getAddresses(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getResources")
    @WebResult(partName = "return")
    public StringArrayResponse getResources(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param data
     * @param addrUUID
     * @param type
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#createAddress")
    @WebResult(partName = "return")
    public StringResponse createAddress(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "addrUUID", partName = "addrUUID")
        String addrUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param sessionID
     * @param addrUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeAddress")
    @WebResult(partName = "return")
    public BoolResponse removeAddress(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "addrUUID", partName = "addrUUID")
        String addrUUID);

    /**
     * 
     * @param sessionID
     * @param addrUUID
     * @return
     *     returns cs.ask.com.TupleArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getAddressData")
    @WebResult(partName = "return")
    public TupleArrayResponse getAddressData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "addrUUID", partName = "addrUUID")
        String addrUUID);

    /**
     * 
     * @param sessionID
     * @param data
     * @param addrUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setAddressData")
    @WebResult(partName = "return")
    public BoolResponse setAddressData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "addrUUID", partName = "addrUUID")
        String addrUUID,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param sessionID
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getAlgorithms")
    @WebResult(partName = "return")
    public StringArrayResponse getAlgorithms(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param direction
     * @param name
     * @param srvUUID
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#createService")
    @WebResult(partName = "return")
    public StringResponse createService(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "direction", partName = "direction")
        String direction);

    /**
     * 
     * @param sessionID
     * @param srvUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeService")
    @WebResult(partName = "return")
    public BoolResponse removeService(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID);

    /**
     * 
     * @param sessionID
     * @param srvUUID
     * @return
     *     returns cs.ask.com.ServiceDataResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getServiceData")
    @WebResult(partName = "return")
    public ServiceDataResponse getServiceData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID);

    /**
     * 
     * @param sessionID
     * @param direction
     * @param name
     * @param srvUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setServiceData")
    @WebResult(partName = "return")
    public BoolResponse setServiceData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "direction", partName = "direction")
        String direction);

    /**
     * 
     * @param stateGroupUUID
     * @param sLayerUUID
     * @param sessionID
     * @param filterValue
     * @param filterDirection
     * @param description
     * @param gauge
     * @param availType
     * @param srvUUID
     * @param resourceTag
     * @param algorithm
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#addServiceLayerToService")
    @WebResult(partName = "return")
    public StringResponse addServiceLayerToService(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "srvUUID", partName = "srvUUID")
        String srvUUID,
        @WebParam(name = "sLayerUUID", partName = "sLayerUUID")
        String sLayerUUID,
        @WebParam(name = "algorithm", partName = "algorithm")
        String algorithm,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "availType", partName = "availType")
        int availType,
        @WebParam(name = "stateGroupUUID", partName = "stateGroupUUID")
        String stateGroupUUID,
        @WebParam(name = "filterDirection", partName = "filterDirection")
        int filterDirection,
        @WebParam(name = "filterValue", partName = "filterValue")
        float filterValue,
        @WebParam(name = "gauge", partName = "gauge")
        boolean gauge,
        @WebParam(name = "resourceTag", partName = "resourceTag")
        String resourceTag);

    /**
     * 
     * @param sLayerUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeServiceLayer")
    @WebResult(partName = "return")
    public BoolResponse removeServiceLayer(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sLayerUUID", partName = "sLayerUUID")
        String sLayerUUID);

    /**
     * 
     * @param sLayerUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.ServiceDataResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getServiceLayerData")
    @WebResult(partName = "return")
    public ServiceDataResponse getServiceLayerData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sLayerUUID", partName = "sLayerUUID")
        String sLayerUUID);

    /**
     * 
     * @param stateGroupUUID
     * @param sLayerUUID
     * @param sessionID
     * @param filterValue
     * @param filterDirection
     * @param description
     * @param gauge
     * @param availType
     * @param resourceTag
     * @param algorithm
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setServiceLayerData")
    @WebResult(partName = "return")
    public BoolResponse setServiceLayerData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "sLayerUUID", partName = "sLayerUUID")
        String sLayerUUID,
        @WebParam(name = "algorithm", partName = "algorithm")
        String algorithm,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "availType", partName = "availType")
        int availType,
        @WebParam(name = "stateGroupUUID", partName = "stateGroupUUID")
        String stateGroupUUID,
        @WebParam(name = "filterDirection", partName = "filterDirection")
        int filterDirection,
        @WebParam(name = "filterValue", partName = "filterValue")
        float filterValue,
        @WebParam(name = "gauge", partName = "gauge")
        boolean gauge,
        @WebParam(name = "resourceTag", partName = "resourceTag")
        String resourceTag);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param planboard
     * @return
     *     returns cs.ask.com.LabelArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getLegend")
    @WebResult(partName = "return")
    public LabelArrayResponse getLegend(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param colour
     * @param sessionID
     * @param name
     * @param stateUUID
     * @param planboard
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#createUserState")
    @WebResult(partName = "return")
    public StringResponse createUserState(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "colour", partName = "colour")
        String colour);

    /**
     * 
     * @param sessionID
     * @param stateUUID
     * @param planboard
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeUserState")
    @WebResult(partName = "return")
    public BoolResponse removeUserState(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard);

    /**
     * 
     * @param sessionID
     * @param stateUUID
     * @param planboard
     * @return
     *     returns cs.ask.com.StateDataResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getUserStateData")
    @WebResult(partName = "return")
    public StateDataResponse getUserStateData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard);

    /**
     * 
     * @param colour
     * @param sessionID
     * @param name
     * @param stateUUID
     * @param planboard
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setUserStateData")
    @WebResult(partName = "return")
    public BoolResponse setUserStateData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "stateUUID", partName = "stateUUID")
        String stateUUID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "colour", partName = "colour")
        String colour);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param start
     * @param end
     * @param planboard
     * @return
     *     returns cs.ask.com.SlotDataArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getSlots")
    @WebResult(partName = "return")
    public SlotDataArrayResponse getSlots(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "start", partName = "start")
        int start,
        @WebParam(name = "end", partName = "end")
        int end);

    /**
     * 
     * @param nodeUUID
     * @param text
     * @param sessionID
     * @param start
     * @param method
     * @param label
     * @param end
     * @param planboard
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#createSlot")
    @WebResult(partName = "return")
    public BoolResponse createSlot(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "start", partName = "start")
        int start,
        @WebParam(name = "end", partName = "end")
        int end,
        @WebParam(name = "label", partName = "label")
        String label,
        @WebParam(name = "method", partName = "method")
        String method,
        @WebParam(name = "text", partName = "text")
        String text);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param start
     * @param label
     * @param end
     * @param planboard
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeSlot")
    @WebResult(partName = "return")
    public BoolResponse removeSlot(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "planboard", partName = "planboard")
        String planboard,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "start", partName = "start")
        int start,
        @WebParam(name = "end", partName = "end")
        int end,
        @WebParam(name = "label", partName = "label")
        String label);

    /**
     * 
     * @param sessionID
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getBoxTypes")
    @WebResult(partName = "return")
    public StringArrayResponse getBoxTypes(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param type
     * @return
     *     returns cs.ask.com.TupleArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getBoxFields")
    @WebResult(partName = "return")
    public TupleArrayResponse getBoxFields(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "type", partName = "type")
        String type);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @param data
     * @param type
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#createBox")
    @WebResult(partName = "return")
    public StringResponse createBox(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeBox")
    @WebResult(partName = "return")
    public BoolResponse removeBox(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @return
     *     returns cs.ask.com.TupleArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getBoxData")
    @WebResult(partName = "return")
    public TupleArrayResponse getBoxData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @param data
     * @param type
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setBoxData")
    @WebResult(partName = "return")
    public BoolResponse setBoxData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "data", partName = "data")
        TupleArray data);

    /**
     * 
     * @param category
     * @param ownUUID
     * @param sessionID
     * @param tag
     * @param description
     * @param name
     * @param value
     * @param resUUID
     * @param type
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#createResource")
    @WebResult(partName = "return")
    public StringResponse createResource(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "ownUUID", partName = "ownUUID")
        String ownUUID,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "category", partName = "category")
        String category,
        @WebParam(name = "tag", partName = "tag")
        String tag,
        @WebParam(name = "value", partName = "value")
        String value);

    /**
     * 
     * @param sessionID
     * @param resUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeResource")
    @WebResult(partName = "return")
    public BoolResponse removeResource(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID);

    /**
     * 
     * @param sessionID
     * @param resUUID
     * @return
     *     returns cs.ask.com.ResourceDataResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getResourceData")
    @WebResult(partName = "return")
    public ResourceDataResponse getResourceData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID);

    /**
     * 
     * @param ownUUID
     * @param sessionID
     * @param tag
     * @param type
     * @return
     *     returns cs.ask.com.ResourceDataResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getResourceDataByTag")
    @WebResult(partName = "return")
    public ResourceDataResponse getResourceDataByTag(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "ownUUID", partName = "ownUUID")
        String ownUUID,
        @WebParam(name = "tag", partName = "tag")
        String tag,
        @WebParam(name = "type", partName = "type")
        String type);

    /**
     * 
     * @param category
     * @param ownUUID
     * @param sessionID
     * @param tag
     * @param description
     * @param name
     * @param value
     * @param resUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setResourceData")
    @WebResult(partName = "return")
    public BoolResponse setResourceData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID,
        @WebParam(name = "ownUUID", partName = "ownUUID")
        String ownUUID,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "category", partName = "category")
        String category,
        @WebParam(name = "tag", partName = "tag")
        String tag,
        @WebParam(name = "value", partName = "value")
        String value);

    /**
     * 
     * @param sessionID
     * @param resUUID
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getDownloadURL")
    @WebResult(partName = "return")
    public StringResponse getDownloadURL(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID);

    /**
     * 
     * @param sessionID
     * @param resUUID
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getUploadURL")
    @WebResult(partName = "return")
    public StringResponse getUploadURL(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "resUUID", partName = "resUUID")
        String resUUID);

    /**
     * 
     * @param sessionID
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getJobTypes")
    @WebResult(partName = "return")
    public StringArrayResponse getJobTypes(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID);

    /**
     * 
     * @param sessionID
     * @param type
     * @return
     *     returns cs.ask.com.TupleArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getJobFields")
    @WebResult(partName = "return")
    public TupleArrayResponse getJobFields(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "type", partName = "type")
        String type);

    /**
     * 
     * @param desc
     * @param sessionID
     * @param interval
     * @param jobUUID
     * @param params
     * @param type
     * @return
     *     returns cs.ask.com.StringResponse
     */
    @WebMethod(action = "urn:com.ask-cs#createJob")
    @WebResult(partName = "return")
    public StringResponse createJob(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "type", partName = "type")
        String type,
        @WebParam(name = "desc", partName = "desc")
        String desc,
        @WebParam(name = "interval", partName = "interval")
        int interval,
        @WebParam(name = "params", partName = "params")
        TupleArray params);

    /**
     * 
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeJob")
    @WebResult(partName = "return")
    public BoolResponse removeJob(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID);

    /**
     * 
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns cs.ask.com.JobDataResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getJobData")
    @WebResult(partName = "return")
    public JobDataResponse getJobData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID);

    /**
     * 
     * @param desc
     * @param sessionID
     * @param interval
     * @param jobUUID
     * @param params
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setJobData")
    @WebResult(partName = "return")
    public BoolResponse setJobData(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "desc", partName = "desc")
        String desc,
        @WebParam(name = "interval", partName = "interval")
        int interval,
        @WebParam(name = "params", partName = "params")
        TupleArray params);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#attachJobToAgent")
    @WebResult(partName = "return")
    public BoolResponse attachJobToAgent(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#detachJobFromAgent")
    @WebResult(partName = "return")
    public BoolResponse detachJobFromAgent(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID);

    /**
     * 
     * @param sessionID
     * @param jobUUID
     * @return
     *     returns cs.ask.com.StringArrayResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getJobAgents")
    @WebResult(partName = "return")
    public StringArrayResponse getJobAgents(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param range
     * @param jobUUID
     * @return
     *     returns cs.ask.com.TransitionResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getTransition")
    @WebResult(partName = "return")
    public TransitionResponse getTransition(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "range", partName = "range")
        int range);

    /**
     * 
     * @param nodeUUID
     * @param nextJobUUID
     * @param overlap
     * @param sessionID
     * @param range
     * @param length
     * @param jobUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setTransition")
    @WebResult(partName = "return")
    public BoolResponse setTransition(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "range", partName = "range")
        int range,
        @WebParam(name = "nextJobUUID", partName = "nextJobUUID")
        String nextJobUUID,
        @WebParam(name = "length", partName = "length")
        int length,
        @WebParam(name = "overlap", partName = "overlap")
        int overlap);

    /**
     * 
     * @param nodeUUID
     * @param sessionID
     * @param range
     * @param jobUUID
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#removeTransition")
    @WebResult(partName = "return")
    public BoolResponse removeTransition(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "jobUUID", partName = "jobUUID")
        String jobUUID,
        @WebParam(name = "nodeUUID", partName = "nodeUUID")
        String nodeUUID,
        @WebParam(name = "range", partName = "range")
        int range);

    /**
     * 
     * @param sessionID
     * @param childUUID
     * @param peerUUID
     * @param parentUUID
     * @param algorithm
     * @return
     *     returns cs.ask.com.IntResponse
     */
    @WebMethod(action = "urn:com.ask-cs#getRate")
    @WebResult(partName = "return")
    public IntResponse getRate(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "algorithm", partName = "algorithm")
        String algorithm,
        @WebParam(name = "parentUUID", partName = "parentUUID")
        String parentUUID,
        @WebParam(name = "childUUID", partName = "childUUID")
        String childUUID,
        @WebParam(name = "peerUUID", partName = "peerUUID")
        String peerUUID);

    /**
     * 
     * @param rate
     * @param sessionID
     * @param childUUID
     * @param peerUUID
     * @param parentUUID
     * @param algorithm
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#setRate")
    @WebResult(partName = "return")
    public BoolResponse setRate(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "algorithm", partName = "algorithm")
        String algorithm,
        @WebParam(name = "parentUUID", partName = "parentUUID")
        String parentUUID,
        @WebParam(name = "childUUID", partName = "childUUID")
        String childUUID,
        @WebParam(name = "peerUUID", partName = "peerUUID")
        String peerUUID,
        @WebParam(name = "rate", partName = "rate")
        float rate);

    /**
     * 
     * @param boxUUID
     * @param sessionID
     * @param toUUID
     * @param fromUUID
     * @param type
     * @return
     *     returns cs.ask.com.BoolResponse
     */
    @WebMethod(action = "urn:com.ask-cs#triggerRequest")
    @WebResult(partName = "return")
    public BoolResponse triggerRequest(
        @WebParam(name = "sessionID", partName = "sessionID")
        String sessionID,
        @WebParam(name = "fromUUID", partName = "fromUUID")
        String fromUUID,
        @WebParam(name = "toUUID", partName = "toUUID")
        String toUUID,
        @WebParam(name = "boxUUID", partName = "boxUUID")
        String boxUUID,
        @WebParam(name = "type", partName = "type")
        String type);

}
